apiVersion: v1
kind: Service
metadata:
  name: webshop-frontend
spec:
  selector:
    app: webshop-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000
  type: NodePort # only for local development purposes. change to LoadBalancer for production